import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import Login from "../Login/Login";

const AuthPage = ({user}) => {
  const router = useRouter();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      if (user) {
        await router.push("/home");
      }
      setLoading(false);
    };

    fetchData();
  }, [user, router]);
  if (loading) return <div>loading...</div>;

  return (
    <>
      <Head>
        <title>Twitter-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Login />
    </>
  );
};

export default AuthPage;
